image: node:12.16.2

pipelines:
  branches:
    master:
      - step:
          name: Build client
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/application.zip
    feature/*:
      - step:
          name: Build client
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/application.zip
